export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
export const SET_CHAIN_ID = 'SET_CHAIN_ID';
export const SET_NETWORK_ID = 'SET_NETWORK_ID';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SET_MONITOR_WALLET = 'SET_MONITOR_WALLET';

export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';
