export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SET_MONITOR_WALLET = 'SET_MONITOR_WALLET';

export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
