export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const TOGGLE_NETWORK = 'TOGGLE_NETWORK';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const REGISTER_MONITOR_WALLET_REQUEST =
  'REGISTER_MONITOR_WALLET_REQUEST';
export const REGISTER_MONITOR_WALLET_SUCCESS =
  'REGISTER_MONITOR_WALLET_SUCCESS';
export const REGISTER_MONITOR_WALLET_FAILED = 'REGISTER_MONITOR_WALLET_FAILED';
