export const tickerData = [
  { pair: 'BTC/USD', change: '12', isPositive: true },
  { pair: 'ETH/USD', change: '5', isPositive: true },
  { pair: 'ADA/USD', change: '1.5', isPositive: false },
  { pair: 'FTX/USD', change: '8', isPositive: true },
  { pair: 'BNB/USD', change: '2.3', isPositive: false },
  { pair: 'XRP/USD', change: '2.3', isPositive: false },
  { pair: 'SOL/USD', change: '2.3', isPositive: true },
  { pair: 'DOGE/USD', change: '2.3', isPositive: false },
];

export const profitBarData = [
  { time: '1 Hour', change: '5', isPositive: false },
  { time: '1 Day', change: '8.1', isPositive: true },
  { time: '1 Week', change: '10.9', isPositive: true },
  { time: '1 Month', change: '12.1', isPositive: true },
];

export const performanceData = [
  {
    coin: 'BTC',
    change: 12,
    isPositive: true,
    price: 36000,
    buyPrice: 18000,
    holdings: 50000,
  },
  {
    coin: 'ETH',
    change: 5,
    isPositive: true,
    price: 3000,
    buyPrice: 1800,
    holdings: 180,
  },
  {
    coin: 'ADA',
    change: 1.5,
    isPositive: false,
    price: 2.24,
    buyPrice: 2.98,
    holdings: 1000,
  },
  {
    coin: 'FTX',
    change: 8,
    isPositive: true,
    price: 60,
    buyPrice: 48,
    holdings: 9900,
  },
  {
    coin: 'BNB',
    change: 2.3,
    isPositive: false,
    price: 20000,
    buyPrice: 25000,
    holdings: 1000,
  },
  {
    coin: 'XRP',
    change: 2.3,
    isPositive: false,
    price: 1.01,
    buyPrice: 1.5,
    holdings: 200,
  },
  {
    coin: 'SOL',
    change: 2.3,
    isPositive: true,
    price: 180,
    buyPrice: 120,
    holdings: 1202,
  },
  {
    coin: 'DOGE',
    change: 2.3,
    isPositive: false,
    price: 0.5,
    buyPrice: 0.6,
    holdings: 100,
  },
];

export const PairPoolData = [
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'BTC',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'BNB',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'BNB',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'BNB',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'BNB',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'ADA',
  },
  {
    date: '12/11/2020',
    sender: 'Binance',
    receiver: 'Rahul',
    amount: 100,
    token: 'SOL',
  },
];
